application: chenji-opensource
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: myproject.wsgi.application
  login: admin

- url: /upload.*
  script: src.upload.application

- url: /serve/.*
  script: src.upload.application

- url: /.*
  script: myproject.wsgi.application



libraries:

- name: django
  version: 1.4
